name: CI

on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  test:
    # permissions:
    #   id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Run tps-action
        uses: hetznercloud/tps-action@main

      - name: Check out repository
        uses: actions/checkout@v3

      - uses: 3bit/setup-hcloud@v2

      - run: hcloud server-type list
