name: CI

on:
  pull_request_target: {}
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      actions: write

    steps:
      - uses: hetznercloud/tps-action@main

      - uses: actions/checkout@v3

      - run: >
          gh workflow run test.yml
          --ref '${{ github.ref }}'
          --field 'hcloud-token=${{ env.HCLOUD_TOKEN }}'
        env:
          GH_TOKEN: ${{ github.token }}
