name: Command

on:
  issue_comment:
    types: [created]

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch command
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          issue-type: pull-request
          commands: |
            test
          dispatch-type: workflow
          event-type-suffix: ""
