name: Test

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: hetznercloud/tps-action@main

      - uses: actions/checkout@v3

      - uses: 3bit/setup-hcloud@v2

      - run: hcloud server-type list
