name: Test

on:
  workflow_dispatch:
    inputs:
      hcloud-token:
        description: Temporary HCLOUD_TOKEN to run the tests
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HCLOUD_TOKEN: ${{ secrets.hcloud-token }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: 3bit/setup-hcloud@v2

      - run: hcloud server-type list
