name: Test

on:
  push:
    branches: [main]
  pull_request:

  workflow_dispatch:
    inputs:
      ref:
        description: Checkout ref
        required: true
        default: $default-branch

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment: integration

    steps:
      - uses: hetznercloud/tps-action@main

      - uses: actions/checkout@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.event.inputs.ref }}

      - uses: actions/checkout@v3
        if: github.event_name != 'workflow_dispatch'

      - uses: 3bit/setup-hcloud@v2

      - run: hcloud server-type list
