name: Test

on:
  push:
    branches: [main]

  repository_dispatch:
    types: [test-command]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HCLOUD_TOKEN: ${{ secrets.hcloud-token }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: 3bit/setup-hcloud@v2

      - run: hcloud server-type list
